language: php

php:
  - 7.2
  - 7.3

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_script:
  - composer update $PREFER_LOWEST

script:
  - composer validate --no-check-all --strict
  - mkdir -p build/logs
  - phpunit --testsuite=unit --coverage-text  --coverage-clover build/logs/clover.xml
  - vendor/bin/phpstan analyze src --level=1
  - vendor/bin/parallel-lint --no-colors --exclude vendor --exclude .idea .
  - vendor/bin/phpdoccheck -d src
  - vendor/bin/phpcpd --ansi src
  - vendor/bin/phpmnd src --non-zero-exit-on-violation
  - vendor/bin/phpcs --standard=psr2 --colors src
  - vendor/bin/phpmd src text phpmd.xml
  - vendor/bin/phploc --ansi src

after_script:
  - vendor/bin/coveralls -v
  - vendor/bin/codacycoverage clover build/logs/clover.xml
